# Generated by Django 5.0.4 on 2024-04-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customeuser_contact_customeuser_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='firstname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
