# Generated by Django 5.0.4 on 2024-04-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_availibility',
            name='edate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product_availibility',
            name='sdate',
            field=models.DateField(),
        ),
    ]
