# Generated by Django 5.0.4 on 2024-04-27 20:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_product_availibility_edate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='edate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='sdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
