# Generated by Django 5.0.4 on 2024-04-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
