# Generated by Django 5.0.4 on 2024-04-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
    ]
