# Generated by Django 5.0.4 on 2024-05-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
