# Generated by Django 5.0.4 on 2024-05-06 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0011_product_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='days',
        ),
    ]
