# Generated by Django 5.0.4 on 2024-05-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0012_remove_product_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_rent_time_status',
            field=models.CharField(choices=[('Day', 'Product Price Per Day'), ('Month', 'Product Price Per Months')], default='Day', max_length=10),
        ),
    ]
